from sqlalchemy import Column, String, Integer

from .database import Base

"""
A class to represent submitted code entries in the database.

Attributes:
    id (int): The primary key for the submitted code entry.
    code (str): The submitted code.
    output (str): The output generated by the submitted code.
"""
class SubmittedCode(Base):
    __tablename__ = "submitted_code"

    id = Column(Integer, primary_key=True, index=True)
    code = Column(String, index=True)
    output = Column(String, index=True)